### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by ritaswc** [rxrw/amap#2]
能不能写个静态方法，比如
Amap::init(['key' => '', .....])
这样子的，这样子框架启动的时候，去设置好，使用具体方法的时候就别管key了，特麻烦

**Comment by rxrw** [comment]
emm 其实是打算写一个的 因为现在比较通用 还没想好怎么引入，因为目前的需求大部分都是一个方法用一次接口 等闲下来优化一下 感谢关注！
