### ISSUE TITLE
代码有输出打印，关一下

### ISSUE THREAD

**Issue by lizhanfei** [rxrw/amap#6]
![image](https://user-images.githubusercontent.com/16754950/85200097-24293c00-b327-11ea-8d56-0e7b8d1b86bd.png)
vendor/reprover/amap/src/Support/Result.php:33

**Comment by rxrw** [comment]
ono sorry

**Comment by hh-Ink** [comment]
composer安装
版本: dev-master


问题还在，希望可以删除后发个版

**Comment by rxrw** [comment]
> composer安装
> 版本: dev-master
> 
> 问题还在，希望可以删除后发个版

周一我看看
